version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./blog.db 
    volumes:
      - sqlite_data:/app
    networks:
      - app-network

  keycloak:
    build: 
      context: ./keycloak
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=dev-file
      - KC_FEATURES=docker
      - KC_HTTP_RELATIVE_PATH=/auth
      - KC_PROXY=edge
      - KC_HOSTNAME_STRICT=false
      - KC_HOSTNAME_STRICT_HTTPS=false
    volumes:
      - ./keycloak/themes:/opt/keycloak/themes
    command:
      - start-dev
      - --hostname=localhost
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
      - keycloak

networks:
  app-network:
    driver: bridge

volumes:
  sqlite_data: