services:
  # Frontend Service
  - type: web
    name: frontend
    env: docker
    region: oregon
    plan: free
    branch: main
    dockerfilePath: ./frontend/Dockerfile
    envVars:
      - key: REACT_APP_API_URL
        fromService:
          name: backend
          type: web
          property: url
      - key: REACT_APP_KEYCLOAK_URL
        fromService:
          name: keycloak
          type: web
          property: url
      - key: REACT_APP_KEYCLOAK_REALM
        value: myrealm
      - key: REACT_APP_KEYCLOAK_CLIENT_ID
        value: my-react-app

  # Backend Service
  - type: web
    name: backend
    env: docker
    region: oregon
    plan: free
    branch: main
    dockerfilePath: ./backend/Dockerfile
    envVars:
      - key: SECRET_KEY
        sync: false
      - key: ALLOWED_HOSTS
        sync: false

  # Keycloak Service
  - type: web
    name: keycloak
    env: docker
    region: oregon
    plan: free
    branch: main
    dockerfilePath: ./keycloak/Dockerfile
    envVars:
      - key: KEYCLOAK_ADMIN
        sync: false
      - key: KEYCLOAK_ADMIN_PASSWORD
        sync: false
      - key: PORT
        value: "8080" 